AgricolaWeb/Models/Finca.cs
namespace AgricolaWeb.Models
{
    public class Finca
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public decimal Hectareas { get; set; }
        public string? Descripcion { get; set; }
    }
}

AgricolaWeb/Controllers/FincasController.cs
using AgricolaWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text;
using System.Text.Json;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using System.Net;


namespace AgricolaWeb.Controllers
{
    public class FincasController : Controller
    {
        private readonly HttpClient _httpClient;

        public FincasController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _httpClient.GetAsync("https://localhost:7274/Fincas/GetAll");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var fincas = JsonSerializer.Deserialize<List<Finca>>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                return View(fincas);
            }

            return View(new List<Finca>()); // Devolver una lista vacía en caso de error
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _httpClient.GetAsync($"https://localhost:7274/Fincas/Details?id={id}");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var finca = JsonSerializer.Deserialize<Finca>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                return View(finca);
            }

            return NotFound();
        }

        public async Task<IActionResult> Create(Finca finca)
        {
            if (!ModelState.IsValid)
            {
                return View(finca); // Devuelve la vista con los datos ingresados si hay errores de validación
            }

            var jsonContent = new StringContent(JsonSerializer.Serialize(finca), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("https://localhost:7274/Fincas/Create", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var result = JsonSerializer.Deserialize<Finca>(jsonString); 
                return RedirectToAction("Index");
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");

            return View(finca); 
        }




        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetAsync($"https://localhost:7274/Fincas/Details?id={id}");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var finca = JsonSerializer.Deserialize<Finca>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                return View(finca);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Finca finca)
        {
            if (!ModelState.IsValid)
            {
                return View(finca);
            }

            var jsonContent = new StringContent(JsonSerializer.Serialize(finca), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"https://localhost:7274/Fincas/Edit?id={id}", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");

            return View(finca);
        }

        
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var finca = await _httpClient.GetFromJsonAsync<Finca>($"https://localhost:7274/Fincas/Details?id={id}");

            if (finca == null)
            {
                return NotFound();
            }

            return View(finca);
        }

        
        [HttpPost, ActionName("Delete")]
        
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync($"https://localhost:7274/Fincas/Delete?id={id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");
            return RedirectToAction("Index");
        }

    }
}

AgricolaWeb/Controllers/LotesController.cs
using AgricolaWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text;
using System.Text.Json;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using System.Net;


namespace AgricolaWeb.Controllers
{
    public class LotesController : Controller
    {
        private readonly HttpClient _httpClient;

        public LotesController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }


        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> GetByFarmId(int farmId)
        {
            
            var response = await _httpClient.GetAsync($"https://localhost:7274/Lotes/GetByFarmId?farmId={farmId}");

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var lotes = JsonSerializer.Deserialize<List<Lotes>>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                TempData["FarmId"] = farmId;
                return View(lotes);
            }

            return View(new List<Lotes>());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _httpClient.GetAsync($"https://localhost:7274/Lotes/Details?id={id}");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var lote = JsonSerializer.Deserialize<Lotes>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                return View(lote);
            }

            return NotFound();
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var response = await _httpClient.GetAsync($"https://localhost:7274/Lotes/Details?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var lote = JsonSerializer.Deserialize<Lotes>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (lote != null)
                {
                    return View(lote); 
                }
            }

            return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, Lotes lote)
        {
            if (!ModelState.IsValid)
            {
                return View(lote);
            }

            var jsonContent = new StringContent(JsonSerializer.Serialize(lote), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"https://localhost:7274/Lotes/Edit/?id={id}", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetByFarmId", new { farmId = lote.IdFinca });
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");

            return View(lote);
        }



        [HttpGet]
        public IActionResult Create()
        {
            
            if (TempData["FarmId"] != null)
            {
                ViewData["FarmId"] = TempData["FarmId"];
                TempData.Keep("FarmId");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Lotes lote)
        {
            if (!ModelState.IsValid)
            {
                if (TempData["FarmId"] != null)
                {
                    ViewData["FarmId"] = TempData["FarmId"];
                    TempData.Keep("FarmId"); 
                }

                return View(lote);
            }

           
            int farmId = (int)TempData["FarmId"];
            lote.IdFinca = farmId;

            var jsonContent = new StringContent(JsonSerializer.Serialize(lote), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("https://localhost:7274/Lotes/Create", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var result = JsonSerializer.Deserialize<Lotes>(jsonString);
                return RedirectToAction("GetByFarmId", new { farmId = lote.IdFinca });
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");
            if (TempData["FarmId"] != null)
            {
                ViewData["FarmId"] = TempData["FarmId"];
                TempData.Keep("FarmId"); // Keep TempData value for the subsequent request
            }


            return View(lote);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lote = await _httpClient.GetFromJsonAsync<Lotes>($"https://localhost:7274/Lotes/Details?id={id}");

            if (lote == null)
            {
                return NotFound();
            }

            return View(lote);
        }



        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync($"https://localhost:7274/Lotes/Delete?id={id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetByFarmId");
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");
            return RedirectToAction("GetByFarmId");
        }









    }
}

AgricolaWeb/Views/Fincas/Create.cshtml
@model AgricolaWeb.Models.Finca

@{
    ViewData["Title"] = "Crear Finca";
}

<h1>Crear Finca</h1>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Ubicacion" class="control-label"></label>
        <input asp-for="Ubicacion" class="form-control" />
        <span asp-validation-for="Ubicacion" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Hectareas" class="control-label"></label>
        <input asp-for="Hectareas" class="form-control" />
        <span asp-validation-for="Hectareas" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Descripcion" class="control-label"></label>
        <input asp-for="Descripcion" class="form-control" />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Crear</button>
</form>

AgricolaWeb/Views/Fincas/Delete.cshtml
@model AgricolaWeb.Models.Finca

@{
    ViewData["Title"] = "Eliminar Finca";
}

<h1>Eliminar Finca</h1>

<h3>¿Está seguro que desea eliminar esta finca?</h3>
<div>
    <h4>Finca</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nombre
        </dt>
        <dd class="col-sm-10">
            @Model.Nombre
        </dd>
        <dt class="col-sm-2">
            Ubicación
        </dt>
        <dd class="col-sm-10">
            @Model.Ubicacion
        </dd>
        <dt class="col-sm-2">
            Hectáreas
        </dt>
        <dd class="col-sm-10">
            @Model.Hectareas
        </dd>
        <dt class="col-sm-2">
            Descripción
        </dt>
        <dd class="col-sm-10">
            @Model.Descripcion
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

AgricolaWeb/Views/Fincas/Details.cshtml
@model AgricolaWeb.Models.Finca

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle</h1>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hectareas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Hectareas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        
    </dl>
</div>

<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index" class="btn btn-primary">Regresar</a>|
    <a asp-action="GetByFarmId" asp-controller="Lotes" asp-route-farmId="@Model.Id" class="btn btn-primary">Lotes</a>
</div>

AgricolaWeb/Views/Fincas/Edit.cshtml
@model AgricolaWeb.Models.Finca
@{
    ViewData["Title"] = "Editar Finca";
}

<h1>Editar Finca</h1>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ubicacion" class="control-label"></label>
        <input asp-for="Ubicacion" class="form-control" />
        <span asp-validation-for="Ubicacion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Hectareas" class="control-label"></label>
        <input asp-for="Hectareas" class="form-control" />
        <span asp-validation-for="Hectareas" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Descripcion" class="control-label"></label>
        <textarea asp-for="Descripcion" class="form-control"></textarea>
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AgricolaWeb/Views/Fincas/Index.cshtml
@model IEnumerable<AgricolaWeb.Models.Finca>

@{
    ViewData["Title"] = "Lista de Fincas";
}

<h1>Lista de Fincas</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Agregar Nueva Finca</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Ubicación
            </th>
            <th>
                Hectáreas
            </th>
            <th>
                Descripción
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ubicacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hectareas)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">
                        <i class="fas fa-info-circle"></i> Detalle
                    </a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">
                        <i class="fas fa-edit"></i> Editar
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">
                        <i class="fas fa-trash-alt"></i> Eliminar
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>