AgricolaWeb/Models/Grupos.cs
namespace AgricolaWeb.Models
{
    public class Grupos
    {
        public int Id { get; set; }

        public int? IdLote { get; set; }

        public string Nombre { get; set; } = null!;
    }
}

AgricolaWeb/Controllers/GruposController.cs
using AgricolaWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text;
using System.Text.Json;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json.Serialization;
using System.Net;


namespace AgricolaWeb.Controllers
{
    public class GruposController : Controller
    {
        private readonly HttpClient _httpClient;

        public GruposController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public ActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetByLotId(int id)
        {
            var response = await _httpClient.GetAsync($"https://localhost:7274/Grupos/GetByLotId?lotId={id}");

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();

                var grupos = JsonSerializer.Deserialize<List<Grupos>>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                TempData["LotId"] = id;
                TempData.Keep("LotId");

                return View(grupos);
            }

            return View(new List<Grupos>());
        }
    

    // GET: GruposController/Details/5
    public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _httpClient.GetAsync($"https://localhost:7274/Grupos/Details?id={id}");
            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var grupo = JsonSerializer.Deserialize<Grupos>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                return View(grupo);
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (TempData["LotId"] != null)
            {
                ViewData["LotId"] = TempData["LotId"];
                TempData.Keep("LotId");
            }
            else
            {
               
                ModelState.AddModelError(string.Empty, "LotId no encontrado.");
                return RedirectToAction("Index", "Lotes");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Grupos grupo)
        {
            if (!ModelState.IsValid)
            {
                if (TempData["LotId"] != null)
                {
                    ViewData["LotId"] = TempData["LotId"];
                    TempData.Keep("LotId");
                }
                return View(grupo);
            }

            if (TempData["LotId"] == null)
            {
                ModelState.AddModelError(string.Empty, "LotId no encontrado en TempData.");
                return View(grupo);
            }

            int lotId = (int)TempData["LotId"];
            grupo.IdLote = lotId;

            var jsonContent = new StringContent(JsonSerializer.Serialize(grupo), Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("https://localhost:7274/Grupos/Create", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetByLotId", new { id = grupo.IdLote });
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");

            if (TempData["LotId"] != null)
            {
                ViewData["LotId"] = TempData["LotId"];
                TempData.Keep("LotId");
            }

            return View(grupo);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var response = await _httpClient.GetAsync($"https://localhost:7274/Grupos/Details?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var grupo = JsonSerializer.Deserialize<Grupos>(jsonString, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (grupo != null)
                {
                    return View(grupo);
                }
            }

            return NotFound();
        }

        
        public async Task<IActionResult> Edit(int id, Grupos grupo)
        {
            if (!ModelState.IsValid)
            {
                return View(grupo);
            }

            var jsonContent = new StringContent(JsonSerializer.Serialize(grupo), Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"https://localhost:7274/Grupos/Edit/?id={id}", jsonContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetByLotId", new { lotId = grupo.IdLote });
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");

            return View(grupo);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupo = await _httpClient.GetFromJsonAsync<Grupos>($"https://localhost:7274/Grupos/Details?id={id}");

            if (grupo == null)
            {
                return NotFound();
            }

            return View(grupo);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _httpClient.DeleteAsync($"https://localhost:7274/Grupos/Delete?id={id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("GetByLotId");
            }

            var errorResponse = await response.Content.ReadAsStringAsync();
            ModelState.AddModelError(string.Empty, $"API error: {errorResponse}");
            return RedirectToAction("GetByLotId");
        }
    }
}

AgricolaWeb/Views/Grupos/Create.cshtml
@model AgricolaWeb.Models.Grupos

@{
    ViewData["Title"] = "Crear Nuevo Grupo";
    int lotId = ViewData["LotId"] != null ? (int)ViewData["LotId"] : 0;
}

<h2>Crear Grupo</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="IdLote" value="@ViewData["LotId"]" />
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AgricolaWeb/Views/Grupos/Delete.cshtml
@model AgricolaWeb.Models.Grupos

@{
    ViewData["Title"] = "Eliminar Grupo";
}

<h2>Confirmar eliminación</h2>

<p>¿Estás seguro que deseas eliminar este grupo?</p>

<div>
    <h4>Grupos</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Nombre
        </dt>
        <dd class="col-sm-10">
            @Model.Nombre
        </dd>
 
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="IdLote" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

AgricolaWeb/Views/Grupos/Details.cshtml
@model AgricolaWeb.Models.Grupos


@{
    ViewData["Title"] = "Detalles del grupo";
}

<table class="table">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Nombre</th>
        <td>@Model.Nombre</td>
    </tr>
</table>

<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id" asp-route-idLote="@Model.IdLote">Editar</a> |
    <a asp-action="GetByFarmId" class="btn btn-primary">Regresar</a>|
</div>

AgricolaWeb/Views/Grupos/Edit.cshtml
@model AgricolaWeb.Models.Grupos

@{
    ViewData["Title"] = "Editar Grupos";
}

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="IdLote" />

    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AgricolaWeb/Views/Grupos/GetByLotId.cshtml
@model List<AgricolaWeb.Models.Grupos>

@{
    ViewData["Title"] = "grupo por Lote";
}

<h1>Grupo por Lote</h1>

<p>
    <a asp-action="Create" asp-controller="Grupos" class="btn btn-primary">Agregar Nuevo Grupo</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Acciones</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var grupo in Model)
        {
            <tr>
                <td>@grupo.Id</td>
                <td>@grupo.Nombre</td>
                <td>
                    <a asp-action="Details" asp-route-id="@grupo.Id" class="btn btn-info">
                        <i class="fas fa-info-circle"></i> Detalle
                    </a>
                    <a asp-action="Edit" asp-route-id="@grupo.Id" class="btn btn-warning">
                        <i class="fas fa-edit"></i> Editar
                    </a>
                    <a asp-action="Delete" asp-route-id="@grupo.Id" class="btn btn-danger">
                        <i class="fas fa-trash-alt"></i> Eliminar
                    </a>
                </td>

            </tr>
        }
    </tbody>
</table>